### PR TITLE
Feat/add ts & plugins

### PR DESCRIPTION
**Pull request by arrlancore**
- Add ts for development
- Add d.ts output
- Add plugins analyzer
- Add public pages for storybook (if use gh pages or we can remove this later if use story deployr)
- Refactor file js => ts
- just remove some component (Box, Layout, Stack) need refactor it to ts actually
- update theme storybook
- change to `index.js` to easier import/use
- [Propose] I think is good to have patter for types like on this link. So each component will have [name].type.ts file (implemented on Button). https://github.com/rajjejosefsson/react-rollup-ts-starter/tree/master/src/components/Button

### CODE REVIEW

**Comment by arrlancore** [comment]
Buil Analyzer 
image

**Review by kfnx — APPROVED** [review]
🔥 🔥 🔥

**Comment by kfnx** [comment]
smh, conflict. sorry my bad
should have wait for this PR to be merged first 🤦

**Comment by arrlancore** [comment]
> smh, conflict. sorry my bad
> should have wait for this PR to be merged first 🤦

fixed it

**Pull request merged**
